version: 2.1

jobs:
  build:
    docker:
      - image: node:14

    steps:
      - checkout

      - run:
          name: Set CI to false
          command: echo "export CI=false" >> $BASH_ENV

      - run:
          name: Install Dependencies and Build
          command: |
            source $BASH_ENV
            npm install
            npm run build

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
